services:
  - type: web
    name: simple-step-flutter
    env: python
    buildCommand: echo "No build needed - using pre-built files"
    startCommand: python server.py
    pullRequestPreviewsEnabled: false
